#!/bin/sh
PYTHON=$(cat $(dirname $(which iython))/.python)
if [ $# -eq 1 ]; then
  case $1 in
    -V | --version)
      echo Iython $(cat $(dirname $(which iython))/.version)
      exit 0
    ;;
    -E | --env)
      echo $PYTHON
      exit 0
    ;;
  esac
fi

while (( $# > 0 ))
do
  case $1 in
    -E | --env)
      ENVIRONMENTS=$(where python3)
      if echo "${ENVIRONMENTS[@]}" | grep -qw $2; then
        PYTHON=$2
        echo $PYTHON > $(dirname $(which iython))/.python
      else
        echo "'$2' path not found"
        exit 1
      fi
      shift
      ;;
    -I | --indent)
      if [[ "$2" = "2" || "$2" = "4" ]]; then
        INDENT=$2
      else
        echo "'$2' is not '2 or 4'"
        exit 1
      fi
      shift
      ;;
    -*)
      echo "option '$1' is not defined"
      exit 1
      ;;
    *)
      if [[ "$FILE" != "" ]]; then
        echo "too many argments"
        exit 1
      fi
      FILE=$1
      if [ ! -e $FILE ]; then
        echo "'${FILE}' is not exist"
        exit 1
      fi
      ;;
  esac
  shift
done

$PYTHON ./example.py
# # echo $(which python3) > $(dirname $(which iython))/.python
# echo $(cat $(dirname $(which iython))/.python)