#!/bin/sh
PYTHON=$(which python3)
INDENT=4
NEWLINE_CODE='\n'
VERSION="0.1.0"
FILE=""
if [ $# -eq 1 ]; then
  case $1 in
    -V | --version)
      echo Iython $VERSION
      exit 0
    ;;
    -E | --env)
      echo Python: $PYTHON
      exit 0
    ;;    
  esac
fi
while (( $# > 0 ))
do
  case $1 in
    -E | --env)
      ENVIRONMENTS=$(where python3)
      if echo "${ENVIRONMENTS[@]}" | grep -qw $2; then
        PYTHON=$2
      else
        echo "'$2' path not found"
        exit 1
      fi
      shift
      ;;
    -I | --indent)
      if [[ "$2" = "2" || "$2" = "4" ]]; then
        INDENT=$2
      else
        echo "'$2' is not '2 or 4'"
        exit 1
      fi
      shift
      ;;
    -*)
      echo "option '$1' is not defined"
      exit 1
      ;;
    *)
      if [[ "$FILE" != "" ]]; then
        echo "too many argments"
        exit 1
      fi
      FILE=$1
      if [ ! -e $FILE ]; then
        echo "'${FILE}' is not exist"
        exit 1
      fi
      ;;
  esac
  shift
done

if [ "$FILE" != "" ]; then
  make_indent() {
    indent=$1
    n=$2
    echo "$(yes "$indent" | head -n $n | tr -d ${NEWLINE_CODE})"
  }

  INDENT=$(echo "$(make_indent " " $INDENT)")
  SCRIPT="if __name__ == '__main__':${NEWLINE_CODE}"
  while IFS= read LINE || [ -n "${LINE}" ]
  do
    SCRIPT="${SCRIPT}$(make_indent "$INDENT" 1)${LINE}${NEWLINE_CODE}"
  done < $FILE

  SCRIPT="${SCRIPT}\
$(make_indent "$INDENT" 1)print('Iython')${NEWLINE_CODE}\
$(make_indent "$INDENT" 1)while True:${NEWLINE_CODE}\
$(make_indent "$INDENT" 2)__value__ = input('>>> ')${NEWLINE_CODE}\
$(make_indent "$INDENT" 2)if __value__ == 'exit()':${NEWLINE_CODE}\
$(make_indent "$INDENT" 3)break${NEWLINE_CODE}\
$(make_indent "$INDENT" 2)elif ' ' not in __value__ and '=' not in __value__ and '(' not in __value__:${NEWLINE_CODE}\
$(make_indent "$INDENT" 3)try:${NEWLINE_CODE}\
$(make_indent "$INDENT" 4)print(eval(__value__, globals(), locals()))${NEWLINE_CODE}\
$(make_indent "$INDENT" 3)except Exception as __exception__:${NEWLINE_CODE}\
$(make_indent "$INDENT" 4)print(__exception__)${NEWLINE_CODE}\
$(make_indent "$INDENT" 2)else:${NEWLINE_CODE}\
$(make_indent "$INDENT" 3)try:${NEWLINE_CODE}\
$(make_indent "$INDENT" 4)exec(__value__, globals(), locals())${NEWLINE_CODE}\
$(make_indent "$INDENT" 3)except Exception as __exception__:${NEWLINE_CODE}\
$(make_indent "$INDENT" 4)print(__exception__)"

  FILE="${FILE%.*}.iython"
  echo "$SCRIPT" > $FILE
  $PYTHON $FILE
  exit 0

else
  echo "missing argument 'FILE'"
  exit 1
fi